config/routes.rb
Rails.application.routes.draw do
  root 'cars#create' #  "root" is equivalent to " get '/' => "
  get '/status'=> 'cars#status'

  get '/cars/accelerate' => 'cars#accelerate'
  get '/cars/light_switch' => 'cars#light_switch'
  get '/cars/brake' => 'cars#brake'

  get '/create' => 'cars#create'
  get '/new' => 'cars#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car
  attr_accessor :make, :model_year, :speed, :lights

  def initialize(make, model_year)
    @make = make
    @model_year = model_year
    @speed = 0
    @lights = "OFF"
  end

  def accelerate
    @speed+=10
  end

  def brake
    @speed >= 7 ? @speed -= 7 : @speed = 0
  end

  def light_switch
    @lights == "OFF" ? @lights = "ON" : @lights = "OFF"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController

  def create
    
  end

  def new
    car = Car.new(params[:make],params[:model_year])
    cookies[:car] = car.to_yaml
    redirect_to '/status'
  end

  def status
    @car = YAML.load(cookies[:car])

    # if session[:make].nil?
    #   cookies[:make] = params[:make]
    #   @make = cookies[:make]
    # end
    #
    # if cookies[:model_year].nil?
    #   cookies[:model_year]= params[:model_year]
    #   @model_year = cookies[:model_year]
    # end
    #
    # if cookies[:speed].nil?
    #   cookies[:speed] = 0
    #   @speed = cookies[:speed]
    # end

    # @make = cookies[:make]
    # @model_year = cookies[:model_year]
    # @speed = cookies[:speed]

  end

  def accelerate
    # Car.new(params[:make],params[:model_year])
    @car = YAML.load(cookies[:car])
    @car.accelerate
    cookies[:car] = @car.to_yaml
    redirect_to '/status'

  end

  def brake

    @car = YAML.load(cookies[:car])
    @car.brake
    cookies[:car] = @car.to_yaml
    redirect_to '/status'

  end

  def light_switch

    @car = YAML.load(cookies[:car])
    @car.light_switch
    cookies[:car] = @car.to_yaml
    redirect_to '/status'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cars/create.html.erb
<h1>Welcome to the Car Simulator!</h1>
<form action = '/new' method = "get">
  <input type = "text" name = "make" placeholder = "MAKE"/>
  <br><br>
  <input type = "text" name = "model_year" placeholder = "MODEL YEAR"/>
  <br><br>
  <input type = "submit" value = "Simulate Car"/>
</form>

app/views/cars/status.html.erb
<h1>This Is Your Car</h1>

<p><b>Make:</b> <%= @car.make %></p>

<p><b>Model Year:</b> <%= @car.model_year%></p>

<p><b>Current Speed: </b> <%= @car.speed %> km/h</p>

<p><b>Light Status: </b> <%= @car.lights %></p>

<%= button_to 'accelerate', cars_accelerate_path, method: :get %>

<%= button_to '    brake    ', cars_brake_path, method: :get %>

<%= button_to 'light switch', cars_light_switch_path, method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CarsProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>